//login
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const UNIQKEY_VERIFY = 'UNIQKEY_VERIFY';

export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

//bussiness 
export const TRADES_PEOPLE= 'TRADES_PEOPLE';
export const TRADES_PEOPLE_SUCCESS = 'TRADES_PEOPLE_SUCCESS';
export const TRADES_PEOPLE_ERROR = 'TRADES_PEOPLE_ERROR';

export const USER_BUSSINESS= 'USER_BUSSINESS';
export const USER_BUSSINESS_SUCCESS = 'USER_BUSSINESS_SUCCESS';
export const USER_BUSSINESS_ERROR = 'USER_BUSSINESS_ERROR';

export const USER_CONTACT_US= 'USER_CONTACT_US';
export const USER_CONTACT_US_SUCCESS = 'USER_CONTACT_US_SUCCESS';
export const USER_CONTACT_US_ERROR = 'USER_CONTACT_US_ERROR';



// profile get user Data
export const USER_DATA = "USER_DATA";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

export const USER_UPDATE ="USER_UPDATE";
export const USER_UPDATE_SUCCESS ="USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR ="USER_UPDATE_ERROR";

export const USER_UPDATE_PROFILE_PHOTO = "USER_UPDATE_PROFILE_PHOTO";
export const USER_UPDATE_PROFILE_PHOTO_SUCCESS = "USER_UPDATE_PROFILE_PHOTO_SUCCESS";
export const USER_UPDATE_PROFILE_PHOTO_ERROR = "USER_UPDATE_PROFILE_PHOTO_ERROR";

export const TRADE_OPTIONS ="TRADE_OPTIONS";
export const TRADE_OPTIONS_SUCCESS ="TRADE_OPTIONS_SUCCESS";
export const TRADE_OPTIONS_ERROR ="TRADE_OPTIONS_ERROR";

export const BUSINESS_SEARCH = "BUSINESS_SEARCH";
export const BUSINESS_SEARCH_SUCCESS = "BUSINESS_SEARCH_SUCCESS";
export const BUSINESS_SEARCH_ERROR = "BUSINESS_SEARCH_ERROR";

export const TRADESPEOPLE_DETAILS = "TRADESPEOPLE_DETAILS";
export const TRADESPEOPLE_DETAILS_SUCCESS = "TRADESPEOPLE_DETAILS_SUCCESS";
export const TRADESPEOPLE_DETAILS_ERROR = "TRADESPEOPLE_DETAILS_ERROR";

export const RECOMMENDATION = "RECOMMENDATION";
export const RECOMMENDATION_SUCCESS = "RECOMMENDATION_SUCCESS";
export const RECOMMENDATION_ERROR = "RECOMMENDATION_ERROR";